name: Web Project CI

on:
  push:
    branches: [main]
    paths:
      - 'StickyNote.Web/**'
      - '.github/workflows/sticky-notes-web_deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./StickyNote.Web

      - name: Build app
        run: npm run build
        working-directory: ./StickyNote.Web

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_POND_03C1D8100 }}
          action: "upload"
          app_location: "/"
          output_location: "build"